# repo-lint dogfooding configuration
mode: strict

ignore:
  - "node_modules/**"
  - "dist/**"
  - ".git/**"
  - ".husky/_/**"
  - "test/fixtures/**"
  - "*.d.ts"
  - "bun.lock"

useGitignore: true

layout:
  type: dir
  children:
    src:
      type: dir
      required: true
      children:
        cli:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        commands:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        config:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
            presets:
              type: dir
              optional: true
              children:
                $files:
                  type: many
                  pattern: "*.ts"
        core:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        rules:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        output:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        cache:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
        types:
          type: dir
          children:
            $files:
              type: many
              pattern: "*.ts"
            $dts:
              type: many
              pattern: "*.d.ts"
              optional: true
        "errors.ts": {}
        "index.ts": {}
        "version.ts": {}
    test:
      type: dir
      required: true
      children:
        $files:
          type: many
          pattern: "*.ts"
        fixtures:
          type: dir
          optional: true
        presets:
          type: dir
          optional: true
          children:
            $files:
              type: many
              pattern: "*.ts"
    ".husky":
      type: dir
      optional: true
      children:
        "pre-commit":
          optional: true
        "commit-msg":
          optional: true
    "package.json":
      required: true
    "tsconfig.json":
      optional: true
    "oxlint.json":
      optional: true
    ".repo-lint.yaml":
      optional: true
    "README.md":
      optional: true
    "LICENSE":
      optional: true
    "CLAUDE.md":
      optional: true
    "knip.json":
      optional: true
    "commitlint.config.js":
      optional: true
    ".gitignore":
      optional: true
    "bunfig.toml":
      optional: true
    "CONTRIBUTING.md":
      optional: true
    "PLAN.md":
      optional: true
    ".github":
      type: dir
      optional: true
      children:
        workflows:
          type: dir
          optional: true
          children:
            $files:
              type: many
              pattern: "*.yml"

rules:
  forbidPaths:
    - "**/node_modules/**"
  forbidNames:
    - ".DS_Store"
    - "Thumbs.db"
